name: build

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Build
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 go build -o bin/sweep
          GOOS=darwin GOARCH=amd64 go build -o bin/sweep-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o bin/sweep-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o bin/sweep.exe

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add bin/
          git diff --quiet && git diff --staged --quiet || (git commit -m 'chore: Update binaries [skip ci]' && git push) 